version: "3.9"
services:
  jupyter-notebook:
    image: samjackmartin/docker-graph-notebook
    # build: ./docker-graph-notebook/
    ports:
      - "8888:8888"
    volumes:
      - ".:/notebook"
    links:
      - gremlin
  gremlin:
    image: samjackmartin/docker-graph-notebook-gremlin-server
    ports:
      - "8182:8182"
