ARG GREMLIN_VERSION=3.5

FROM tinkerpop/gremlin-server:$GREMLIN_VERSION

COPY ./conf/gremlin-server.yaml /opt/gremlin-server/conf/gremlin-server.yaml
COPY ./conf/tinkergraph-empty.properties /opt/gremlin-server/conf/tinkergraph-empty.properties
