name: Smoke Tests
on: [push]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run docker compose tests
        run: |
          docker compose up -d
          sleep 30
          docker compose ps
          docker compose ps | (! grep 'unhealthy\|starting')
          docker compose stop -t 1
        working-directory: test
