on: push
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run docker compose tests
        run: |
          docker compose up -d
          sleep 20
          docker compose ps
          docker compose ps | grep unhealthy
          docker compose stop -f
        working-directory: test
